<a href="https://colab.research.google.com/github/Andrew-Kimmaker/codyssey/blob/main/Example_Code_02_K_means_clustering_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import numpy as np
import matplotlib.pylab as plt
from skimage import io
from google.colab.patches import cv2_imshow

# 01. For-loop

In [ ]:
for i in range(10):

    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
j = 0

for i in range(10):

    j = j + 1
    print(j)

    if j > 5:
        break

1
2
3
4
5
6


# 02. Distance matrix

## 2-1. From scratch, build a distance function

In [ ]:
v = [3, 4]

dist = 0

for i in v:
    dist = dist + i**2

dist = dist**0.5
print(dist)

5.0


In [ ]:
p1 = [2, 5]
p2 = [6, 8]

dist = 0

for i in range(len(p1)):
    dist = dist + (p1[i] - p2[i])**2

dist = dist**0.5
print(dist)

5.0


In [ ]:
def distance(p1, p2):
    dist = 0
    for i in range(len(p1)):
        dist = dist + (p1[i] - p2[i])**2
    dist = dist**0.5
    return dist

In [ ]:
distance(p1, p2)

5.0

## 2-2. np.linalg.norm

In [ ]:
v = np.array([3, 4])
length = np.linalg.norm(v)   # √(3² + 4²) = 5
print(length)                # 5.0


5.0


In [ ]:
p1 = np.array([2, 5])
p2 = np.array([6, 8])
distance = np.linalg.norm(p1 - p2)  # √((6-2)² + (8-5)²)
print(distance)                      # 5.0

5.0


In [ ]:
points = np.array([[0,0], [1,1], [2,2]])
centroids = np.array([[0,1], [2,0]])

# distances[i, j] = distance from points[i] to centroids[j]
# numpy broadcast
distances = np.linalg.norm(points[:, None] - centroids[None, :], axis=2)
print(distances)

[[1.         2.        ]
 [1.         1.41421356]
 [2.23606798 2.        ]]


# 03. Lables (np.argmin)

`axis=1` → column index of min in each row.

`axis=0` → row index of min in each column.

In [ ]:
arr = np.array([8, 3, 5, 1])
idx = np.argmin(arr)   # position of the smallest value

print(idx)             # 3
print(arr[idx])        # 1

3
1


In [ ]:
matrix = np.array([[10, 2, 8],
                   [ 5, 7, 1]])

# column index of the minimum in each row
col_idx = np.argmin(matrix, axis=1)
print(col_idx)         # [1 2]

[1 2]


# 04. Random choice

In [ ]:
np.random.choice(3)

0

In [ ]:
np.random.choice(3, 3)

array([1, 1, 2])

In [ ]:
matrix = np.array([[10, 2, 8],
                   [ 5, 7, 1],
                   [2, 3, 4]])

# 05. K-means

In [ ]:
# ----- 1. Data: eight points A–H -----
points = np.array([
    [2,10],  # A
    [2, 5],  # B
    [8, 4],  # C
    [5, 8],  # D
    [7, 5],  # E
    [6, 4],  # F
    [1, 2],  # G
    [4, 9]   # H
])

# ----- 2. Parameters -----
k = 3                 # number of clusters
max_iter = 100
tol = 1e-4
np.random.seed(0)     # reproducible


In [ ]:
centroids = np.array([
    [2,10],  # A
    [5, 8],  # D
    [1, 2],  # G
])

In [ ]:
distances = np.linalg.norm(points[:, None] - centroids[None, :], axis=2)
distances

array([[0.        , 3.60555128, 8.06225775],
       [5.        , 4.24264069, 3.16227766],
       [8.48528137, 5.        , 7.28010989],
       [3.60555128, 0.        , 7.21110255],
       [7.07106781, 3.60555128, 6.70820393],
       [7.21110255, 4.12310563, 5.38516481],
       [8.06225775, 7.21110255, 0.        ],
       [2.23606798, 1.41421356, 7.61577311]])

In [ ]:
labels = np.argmin(distances, axis=1)
labels

array([0, 2, 1, 1, 1, 1, 2, 1])

In [ ]:
new_centroids = np.array([points[labels == i].mean(axis=0) for i in range(k)])
new_centroids

array([[ 2. , 10. ],
       [ 6. ,  6. ],
       [ 1.5,  3.5]])

# 06 Execise: collect above 3 cells into a for-loop or while-loop, to calculate the final Centro_ids and labels (cluster)

In [ ]:
# ----- 3. Randomly choose initial centroids -----


# ----- 4. K-means loop -----

# 07 Execise: create a k-means function

# 08 Visualization

In [ ]:
centroids, labels = your_function_name(
    points=points,
    k=3,
    max_iter=100
)

plt.scatter(points[:, 0], points[:, 1], c=labels)

plt.scatter(
    centroids[:, 0],
    centroids[:, 1],
    marker='X',
    s=200
)

plt.xlabel("X")
plt.ylabel("Y")
plt.title("K-means Clustering")

plt.show()